services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: boardgames
      POSTGRES_PASSWORD: boardgames123
      POSTGRES_DB: boardgames
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: